entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: c3r5b8.dev
            sans:
              - "*.c3r5b8.dev"
    http3:
      advertisedPort: 443
providers:
  file:
    directory: "/etc/traefik/dynamic_conf"
    watch: true
  docker:
    exposedByDefault: false
api:
  insecure: true
certificatesResolvers:
  letsencrypt:
    acme:
      storage: /etc/traefik/acme/acme.json
      email: olespid@gmail.com
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
