keys:
  - &hosts:
    - &antares age1t27dp24z8suvgewhkmkd3wtlx0xefah6z3zpqh8zpyk5usvqccfsu8c7uh
    - &sargas age1m4vwlkxfrfsy90yfdj8ujquvjlujs2r7wsu4e560gg08q5fys5dqu6z54n
creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *antares
      - *sargas
