keys:
  - &hosts:
    - &antares age1snamtmqdmphjgyjvm3zr59g59qu6qdfvc8cclkc8zyjv2atvk5ysn54qw2
    - &sargas age1m4vwlkxfrfsy90yfdj8ujquvjlujs2r7wsu4e560gg08q5fys5dqu6z54n
creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *antares
      - *sargas
