keys:
  - &hosts:
    - &antares age1nnedvxpqyqkrhezz299qsw9kezxu7n6rz3kzpwz3hkfrvy63muqqvp0c29
creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *antares
