keys:
  - &hosts:
    - &antares age1n7hd8c38038734ckw4s5sdf9yx03f9xl94e8pvue6wve4nu7v5eqnfr7ps
    - &sargas age1m4vwlkxfrfsy90yfdj8ujquvjlujs2r7wsu4e560gg08q5fys5dqu6z54n
creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *antares
      - *sargas
