services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/home/c3r5b8/dev/nix-config/system/docker/configs/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro"
      - "/home/c3r5b8/dev/nix-config/system/docker/configs/traefik/dynamic_conf:/etc/traefik/dynamic_conf:ro"
      - "/var/lib/homelab/traefik/acme.json:/etc/traefik/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`proxy.c3r5b8.dev`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`pass.c3r5b8.dev`)"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
    volumes:
      - /var/lib/homelab/vaultwarden:/data
    environment:
      - DOMAIN=https://pass.c3r5b8.dev
      - WEBSOCKET_ENABLED=true
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Kyiv
      - WEBUI_PORT=8080
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
      - TORRENTING_PORT=6881
    volumes:
      - /var/lib/homelab/qbittorrent:/config
      - /mnt/media:/downloads
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorent.rule=Host(`qb.c3r5b8.dev`)"
      - "traefik.http.services.qbittorent.loadbalancer.server.port=8080"
  technitium:
    container_name: technitium
    hostname: technitium
    image: technitium/dns-server:latest
    network_mode: "host"
    # ports:
      # - "5380:5380/tcp" #DNS web console (HTTP)
      # - "53:53/udp" #DNS service
      # - "53:53/tcp" #DNS service
    environment:
      - DNS_SERVER_DOMAIN=technitium
      - DNS_SERVER_ADMIN_PASSWORD=${DNS_SERVER_ADMIN_PASSWORD}
      - DNS_SERVER_WEB_SERVICE_ENABLE_HTTPS=false
      - DNS_SERVER_FORWARDERS=1.1.1.1, 8.8.8.8
      - DNS_SERVER_FORWARDER_PROTOCOL=Tcp
      - DNS_SERVER_LOG_USING_LOCAL_TIME=true
    volumes:
      - /var/lib/homelab/technitium:/etc/dns
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.technitium.rule=Host(`dns.c3r5b8.dev`)"
      - "traefik.http.services.technitium.loadbalancer.server.port=5380"
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    environment:
      - TZ=Europe/Kyiv
      - PUID=1000
      - PGID=100
    volumes:
      - /mnt/media:/media
      - /var/lib/homelab/audiobookshelf/config:/config
      - /var/lib/homelab/audiobookshelf/metadata:/metadata
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.audiobookshelf.rule=Host(`audiobooks.c3r5b8.dev`)"
      - "traefik.http.services.audiobookshelf.loadbalancer.server.port=80"
    restart: unless-stopped
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Kyiv
    volumes:
      - /var/lib/homelab/jellyfin:/config
      - /mnt/media:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.c3r5b8.dev`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    restart: unless-stopped
