{pkgs, ...}: {
  imports = [
    ./containers/audiobookshelf
    ./containers/traefik
    ./containers/multi-scrobbler
    ./containers/qbittorrent
    ./containers/vaultwarden
  ];
  systemd.services."podman-network-homelab_default" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f homelab_default";
    };
    script = ''
      podman network inspect homelab_default || podman network create homelab_default
    '';
    partOf = ["podman-compose-homelab-root.target"];
    wantedBy = ["podman-compose-homelab-root.target"];
  };

  systemd.targets."podman-compose-homelab-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
